name: Build All Metapackage

on:
  push:
    branches: [main, master]
    paths:
      - "build_deb.sh"
      - "*.txt"
      - ".github/workflows/build-deb.yml"
    tags:
      - "v*"
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Deb Packages
        run: |
          chmod +x build_deb.sh
          echo ">>> Building for robopi1..."
          ./build_deb.sh robopi1
          echo ">>> Building for robopi2..."
          ./build_deb.sh robopi2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roboto-all-debs
          path: "*.deb"
